# Generated by Django 5.0.2 on 2024-04-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id_devices', models.IntegerField(max_length=3, primary_key=True, serialize=False)),
                ('serial', models.IntegerField(max_length=9)),
                ('imel', models.IntegerField(max_length=16)),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'devices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evet',
            fields=[
                ('id_log', models.IntegerField(primary_key=True, serialize=False)),
                ('date_local', models.TimeField()),
                ('status', models.IntegerField(max_length=1)),
                ('depth', models.IntegerField(max_length=3)),
                ('power', models.IntegerField(max_length=3)),
            ],
            options={
                'db_table': 'log_event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id_log', models.IntegerField(primary_key=True, serialize=False)),
                ('date_local', models.TimeField()),
                ('status', models.IntegerField(max_length=1)),
                ('depth', models.IntegerField(max_length=3)),
                ('power', models.IntegerField(max_length=3)),
            ],
            options={
                'db_table': 'log_time',
                'managed': False,
            },
        ),
    ]
