# Generated by Django 5.0.2 on 2024-05-17 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20240511_1920'),
    ]

    operations = [
    ]
