# Generated by Django 5.0.2 on 2024-05-22 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20240517_2202'),
    ]

    operations = [
    ]
