# Generated by Django 5.0.2 on 2024-05-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20240522_1828'),
    ]

    operations = [
    ]
