# Generated by Django 5.0.2 on 2024-05-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20240522_1833'),
    ]

    operations = [
    ]
