# Generated by Django 5.0.2 on 2024-05-23 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20240522_1842'),
    ]

    operations = [
    ]
