# Generated by Django 5.0.2 on 2024-05-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20240523_1405'),
    ]

    operations = [
    ]
