# Generated by Django 5.0.2 on 2024-05-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20240523_1415'),
    ]

    operations = [
    ]
